# Run hostapd as a RADIUS server
radius_server_clients=hostapd.radius_clients
radius_server_auth_port=1812

eap_server=1
# For EAP user file see section 5.3
eap_user_file=hostapd.eap_user

# TLS parameters (shared by EAP-PEAP, EAP-TTLS, EAP-FAST)
ca_cert=ca.pem
# Server certificate and private key from separate files
server_cert=server.pem
private_key=server-key.pem
private_key_passwd=whatever
